# Generated by Django 4.2.1 on 2023-08-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_First_Name', models.CharField(max_length=25)),
                ('patient_Last_Name', models.CharField(max_length=25)),
                ('contect', models.CharField(max_length=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=8)),
                ('address', models.TextField(default='')),
                ('DOB', models.DateField()),
                ('medical_Conditions', models.TextField(default='')),
                ('past_Surgeries_or_Hospitalizations', models.TextField(default='')),
                ('known_allergies', models.TextField(default='')),
                ('currently_medications_or_supplements', models.TextField(default='')),
                ('current_Symptoms_or_issue', models.TextField(default='')),
                ('current_symptoms_started', models.DateField(blank=True, default=None, null=True)),
                ('current_symptoms_detail', models.TextField(default='')),
                ('smokeing_or_tobacco_or_alcohol', models.BooleanField(default=False)),
                ('physically_Activety', models.TextField(default='')),
                ('diet', models.TextField(default='')),
                ('mental_Health', models.TextField(default='')),
                ('Immunization_History', models.TextField(default='')),
                ('women_Health', models.TextField(default='')),
                ('other_Health_Concerns', models.TextField(default='')),
                ('weight', models.CharField(default='', max_length=5)),
                ('clinc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_patient_clinic', to='Accounts.clinic')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_patient_staff', to='Accounts.staff')),
            ],
            options={
                'db_table': 'patient_information',
            },
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_medicine', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=6)),
                ('formulation', models.CharField(choices=[('tablet', 'tablet'), ('Capsule', 'Capsule'), ('Syrup', 'syrup'), ('Injection', 'injection')], default='tablet', max_length=100)),
                ('drug_Class', models.CharField(choices=[('Antibiotic', 'antibiotic'), ('Biotic', 'biotic')], default='Antibiotic', max_length=100)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicines', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.clinic')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='doc_non_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('doctor_non_availability_date', models.DateField()),
                ('slots', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_patient_clinic', to='Accounts.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.doctor')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_patient_staff', to='Accounts.staff')),
            ],
            options={
                'db_table': 'doc_non_availability',
            },
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_appointment', models.DateField()),
                ('close', models.BooleanField(default=False)),
                ('slots', models.TimeField(choices=[('10:00:00', '10:00:00'), ('10:15:00', '10:15:00'), ('10:30:00', '10:30:00'), ('10:45:00', '10:45:00'), ('11:00:00', '11:00:00'), ('11:15:00', '11:15:00'), ('11:30:00', '11:30:00'), ('11:45:00', '11:45:00'), ('12:00:00', '12:00:00'), ('12:15:00', '12:15:00'), ('12:30:00', '12:30:00'), ('12:45:00', '12:45:00'), ('13:00:00', '13:00:00'), ('13:15:00', '13:15:00'), ('13:30:00', '13:30:00'), ('13:45:00', '13:45:00'), ('14:00:00', '14:00:00'), ('14:15:00', '14:15:00'), ('14:30:00', '14:30:00'), ('14:45:00', '14:45:00'), ('15:00:00', '15:00:00'), ('15:15:00', '15:15:00'), ('15:30:00', '15:30:00'), ('15:45:00', '15:45:00'), ('16:00:00', '16:00:00'), ('16:15:00', '16:15:00'), ('16:30:00', '16:30:00'), ('16:45:00', '16:45:00'), ('17:00:00', '17:00:00'), ('17:15:00', '17:15:00'), ('17:30:00', '17:30:00'), ('17:45:00', '17:45:00'), ('18:00:00', '18:00:00'), ('18:15:00', '18:15:00'), ('18:30:00', '18:30:00'), ('18:45:00', '18:45:00')])),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('clinc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_patient_clinic', to='Accounts.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_clinic', to='Accounts.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.patient_information')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
