# Generated by Django 4.2.1 on 2023-08-11 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image_and_logo', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='images_and_logo')),
                ('type', models.CharField(choices=[('CLINIC', 'clinic'), ('STAFF', 'staff'), ('DOCTOR', 'doctor')], default='CLINIC', max_length=8)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('clinic_Name', models.CharField(default='', max_length=50)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_clinic', models.BooleanField(default=False)),
                ('Owner_First_Name', models.CharField(default='', max_length=25)),
                ('Owner_Last_Name', models.CharField(default='', max_length=25)),
                ('first_Name', models.CharField(default='', max_length=25)),
                ('last_Name', models.CharField(default='', max_length=25)),
                ('designation', models.TextField(default='')),
                ('experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)])),
                ('qualification', models.TextField(default='')),
                ('specialist', models.TextField(default='')),
                ('contact', models.CharField(max_length=10)),
                ('Block', models.BooleanField(default=False)),
                ('map', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Accounts.useraccount',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Accounts.useraccount',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Accounts.useraccount',),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_accounts_clinic', to='Accounts.clinic'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_accounts_staff', to='Accounts.staff'),
        ),
    ]
